[[repos]]
project = "dev-team/api"
branches = ["mysql_db"]
emails = ["23826299@qq.com"]

[[repos]]
project = "dev-team/flint"
branches = ["main"]

[[repos]]
project = "dev-team/horizon"
branches = ["test/gpu"]

[[repos]]
project = "dev-team/api-manager-platform"
branches = ["main"]
emails = ["lj-emilia@qq.com"]

[[repos]]
project = "dev-team/dogress"
branches = ["main"]
